# *KNN Algorithm from scratch*

K nearest neigbhour algorithm belongs to the family of Supervised learning. It is used to solve both regression and classification problems.

##### What happens in K-nearest neigbour algorithm? and How does it give us predictions?

K-nearest algorithm assumes that any data point will have similar properties of its nearest K points.

KNN computes the distance b/w our query point to every data point, It sorts the data points in the ascending order of their distances and picks first k number of neighbors.  
After picking first k neighbours(i.e first k data points) if it is a regression problem it computes mean,if it is a classification problem it does majority voting and gives us the result.

For more understanding of KNN refer the below blog.

https://www.analyticsvidhya.com/blog/2021/05/knn-the-distance-based-machine-learning-algorithm/

# Building KNN regressor from scratch

using numpy broadcasting,basic numpy operations and basic math functions here we are building an efficient knn model

##### What is numpy broadcasting?

numpy has a special feature called numpy broadcasting. Let us understand using the following example in the below example we can see 2 arrays a and b. and below sum of a and b is computed and it resulted in c.
Can we add two matrices of different dimensions? According to matrix addition No we cannot do that. But in numpy arrays with the help of broad casting we can add 2 arrays of different shapes.(one must be a 1-D array)

after adding a(shape 3x3) and b(shape 3x1) it resulted in c  i.e here ([1, 1, 1]) is casted 3 times to match the dimensionality of a.

In [7]:
a.shape

(3, 3)

In [8]:
b.shape

(3,)

In [3]:
import numpy as np

In [15]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([1,1,1])
print(a)
print('*******'*2)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
**************
[1 1 1]


In [11]:
c=a+b

In [12]:
c

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

we are passing X_train,X_test and No.of neighbors to our function knn_reg and it returns y_predict(i.e predicted value of each test data point).

1)using numpy broadcasting we compute the array of distances of each data point from query point.
       
       
"(np.sqrt(np.sum(np.square(p.values-q.values[i]),axis=1)))"

2) Then we can sort the distances using argsort so that it will return us the indices of the sorted distances.

3) After step 2 we restore the original indices using the indices array we created inorder to get the y values(i.e target variable) 

4) compute the mean of first K using slicing operations and add them to the respective y_predict zeros numoy array we created in every iteration until all the y_predict values are computed from the X_test

In [ ]:
def knn_reg(p,q,K):
    y_predict=np.zeros(q.shape[0])
    indices=np.array(p.index)
    for i in range (len(q)):
        distances=(np.sqrt(np.sum(np.square(p.values-q.values[i]),axis=1)))
        y_predict[i]=y_predict[i]+y[indices[np.argsort(distances)]].values[:K].mean() 
    return y_predict

$$$------------------$$$------------------$$$